# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from Serial_Send/Serial_Send.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Serial_Send(genpy.Message):
  _md5sum = "33a15562caea82466375017bafdca201"
  _type = "Serial_Send/Serial_Send"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 gimbal_x
float32 gimbal_y
float32 gimbal_z
float32 vx_set
float32 vy_set
float32 wz_set
"""
  __slots__ = ['gimbal_x','gimbal_y','gimbal_z','vx_set','vy_set','wz_set']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gimbal_x,gimbal_y,gimbal_z,vx_set,vy_set,wz_set

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Serial_Send, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.gimbal_x is None:
        self.gimbal_x = 0.
      if self.gimbal_y is None:
        self.gimbal_y = 0.
      if self.gimbal_z is None:
        self.gimbal_z = 0.
      if self.vx_set is None:
        self.vx_set = 0.
      if self.vy_set is None:
        self.vy_set = 0.
      if self.wz_set is None:
        self.wz_set = 0.
    else:
      self.gimbal_x = 0.
      self.gimbal_y = 0.
      self.gimbal_z = 0.
      self.vx_set = 0.
      self.vy_set = 0.
      self.wz_set = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.gimbal_x, _x.gimbal_y, _x.gimbal_z, _x.vx_set, _x.vy_set, _x.wz_set))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.gimbal_x, _x.gimbal_y, _x.gimbal_z, _x.vx_set, _x.vy_set, _x.wz_set,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.gimbal_x, _x.gimbal_y, _x.gimbal_z, _x.vx_set, _x.vy_set, _x.wz_set))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.gimbal_x, _x.gimbal_y, _x.gimbal_z, _x.vx_set, _x.vy_set, _x.wz_set,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
