// Generated by gencpp from file serial_send/Serial_Send.msg
// DO NOT EDIT!


#ifndef SERIAL_SEND_MESSAGE_SERIAL_SEND_H
#define SERIAL_SEND_MESSAGE_SERIAL_SEND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_send
{
template <class ContainerAllocator>
struct Serial_Send_
{
  typedef Serial_Send_<ContainerAllocator> Type;

  Serial_Send_()
    : vx_set(0.0)
    , vy_set(0.0)
    , wz_set(0.0)
    , yaw_add(0.0)
    , pitch_add(0.0)
    , mode(0)  {
    }
  Serial_Send_(const ContainerAllocator& _alloc)
    : vx_set(0.0)
    , vy_set(0.0)
    , wz_set(0.0)
    , yaw_add(0.0)
    , pitch_add(0.0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef float _vx_set_type;
  _vx_set_type vx_set;

   typedef float _vy_set_type;
  _vy_set_type vy_set;

   typedef float _wz_set_type;
  _wz_set_type wz_set;

   typedef float _yaw_add_type;
  _yaw_add_type yaw_add;

   typedef float _pitch_add_type;
  _pitch_add_type pitch_add;

   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::serial_send::Serial_Send_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_send::Serial_Send_<ContainerAllocator> const> ConstPtr;

}; // struct Serial_Send_

typedef ::serial_send::Serial_Send_<std::allocator<void> > Serial_Send;

typedef boost::shared_ptr< ::serial_send::Serial_Send > Serial_SendPtr;
typedef boost::shared_ptr< ::serial_send::Serial_Send const> Serial_SendConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_send::Serial_Send_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_send::Serial_Send_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_send::Serial_Send_<ContainerAllocator1> & lhs, const ::serial_send::Serial_Send_<ContainerAllocator2> & rhs)
{
  return lhs.vx_set == rhs.vx_set &&
    lhs.vy_set == rhs.vy_set &&
    lhs.wz_set == rhs.wz_set &&
    lhs.yaw_add == rhs.yaw_add &&
    lhs.pitch_add == rhs.pitch_add &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_send::Serial_Send_<ContainerAllocator1> & lhs, const ::serial_send::Serial_Send_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_send

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::serial_send::Serial_Send_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_send::Serial_Send_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_send::Serial_Send_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_send::Serial_Send_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_send::Serial_Send_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_send::Serial_Send_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_send::Serial_Send_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73de9545dab8a1f88fa0fdc921aa3bba";
  }

  static const char* value(const ::serial_send::Serial_Send_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73de9545dab8a1f8ULL;
  static const uint64_t static_value2 = 0x8fa0fdc921aa3bbaULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_send::Serial_Send_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_send/Serial_Send";
  }

  static const char* value(const ::serial_send::Serial_Send_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_send::Serial_Send_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vx_set\n"
"float32 vy_set\n"
"float32 wz_set\n"
"float32 yaw_add\n"
"float32 pitch_add\n"
"uint8 mode\n"
;
  }

  static const char* value(const ::serial_send::Serial_Send_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_send::Serial_Send_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx_set);
      stream.next(m.vy_set);
      stream.next(m.wz_set);
      stream.next(m.yaw_add);
      stream.next(m.pitch_add);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Serial_Send_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_send::Serial_Send_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_send::Serial_Send_<ContainerAllocator>& v)
  {
    s << indent << "vx_set: ";
    Printer<float>::stream(s, indent + "  ", v.vx_set);
    s << indent << "vy_set: ";
    Printer<float>::stream(s, indent + "  ", v.vy_set);
    s << indent << "wz_set: ";
    Printer<float>::stream(s, indent + "  ", v.wz_set);
    s << indent << "yaw_add: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_add);
    s << indent << "pitch_add: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_add);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_SEND_MESSAGE_SERIAL_SEND_H
